### PR TITLE
LRQA-64698 Update the selector FORM_FIELD_FIRST_ITEM

### PR DESCRIPTION
**Pull request by guipfreire**

### CODE REVIEW

**Comment by guipfreire** [comment]
ci:test:sf

**Comment by guipfreire** [comment]
ci:test:relevant

**Comment by guipfreire** [comment]
ci:reevaluate:1232004_7300

**Comment by yichenroy** [comment]
ci:test:relevant
See if the issue with `ProjectTemplatesRESTBuilderTest.testCompareRESTBuilderPluginVersions` is consistent

**Comment by guipfreire** [comment]
ci:forward

**Pull request closed without merging**
