### PR TITLE
LRQA-57661 Remove the test from quarantine.

### PR DESCRIPTION
**Pull request by guipfreire**

### CODE REVIEW

**Comment by guipfreire** [comment]
ci:test:sf

**Comment by guipfreire** [comment]
ci:test:relevant

**Comment by guipfreire** [comment]
ci:forward

**Comment by guipfreire** [comment]
ci:help

**Comment by gabrielwas** [comment]
ci:forward

**Comment by gabrielwas** [comment]
ci:forward

**Pull request closed without merging**
