### PR TITLE
LRQA-57661 Text fix. A macro was created to assert that the Save button is disabled

### PR DESCRIPTION
**Pull request by guipfreire**

### CODE REVIEW

**Comment by guipfreire** [comment]
CI:help

**Comment by guipfreire** [comment]
ci:help

**Comment by guipfreire** [comment]
ci:test:sf

**Comment by guipfreire** [comment]
ci:reopen

**Comment by guipfreire** [comment]
ci:test:sf

**Comment by palomaanunes** [comment]
ci:test:sf

**Comment by palomaanunes** [comment]
ci:help

**Comment by palomaanunes** [comment]
ci:test:sf

**Comment by guipfreire** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by guipfreire** [comment]
ci:test:sf

**Pull request closed without merging**
